language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  sauce_connect: true
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi
env:
  global:
  - secure: 1FVaPmTGH7l3mrg6J1ZIKNp4t+lVXlsPKtmQBhUpz1JzDR32iWX2tzD/SvaJVuZBaixcwTRv1UUES37YcpV1uTANvRqqISM9dtQSGwdGIRyODMSKzqNfnD9HYdZSDeY8oB2JUTwxt2urZ+hsQ363jcXwdBjm6LU3bJOXlNw6jR3r+kY7aaPRkudJJe5BOZOgwfT/yFxqXO1mQA5RQUUXGtR2tA/ShkC8P/16u6/fPJLrYAOeSkX82T6yc+8T+IfK49qF/x8whA+tJJAFSrxIwdmLYzASXaNvczduDrML3KQqQ3h8N71r21571hmmoeXSbFvqpjDIpFNdgRfFm7xpLi4pGiHqNGpLyh/anor/ZWEhyLo4PRe85pl5lmJNO3RJAFtBOX9WLpZ9tvVhZmkJljx/IuX7Yp00wtN14DIMzVDRuQIMr6y1tdwPjhWJ/bLEXq5XqffaaeOsOmSgtvWJzgNcqYBeREJXAZs9JEtZ9OTIZqqLJSf5m/QKl0qOmxLjEVxNGFP/ae41kUzreWAk+ypnPXkKfnl/7TVJkLERXo+wrVWdMEUdV+WoRVI8NRqoYz2qgq0tWaLJb4fTr1lr/xHghqIRwGioNnhS+jwpGvHqw9xPyJKCes31RkdirnrHqCnHutiWyqD7AD9eZfr/po0Io7zIW0SgrIC5CMYcweU=
  - secure: xC3X8ufSpZcVIZZb5VRfhPTK+cbAFXfN2nvA8j/WxwS8oZx58IpzFWTtNQf4nDJk1hwuZeBzoL+7HpAkn276KYShcMxOKk/WSWlJmpTTNN0qbWwPnJwxgX1dZSXcONRl8E9iU7m/5kBYaHa0wp2vVGynKsJ3Cx1tySFbKj5DKCbMvhy14JjKPM0buaHi7Gly5xhmmu8Zk+RG/6/cYY96F5S9NLJjdkH3q57l0UdFaeYjCuHhpuXyn2Fu9h3r+75PVcyCy22Y9ixQvfLLMWGdJPf06gMdGAOkWcRWNm8D/kB8lEaTxB+O3ckd3NhTgfIAs4tl1Rak/CRSOMXYAT2xjkgThQoED8+cL8LdaY7KzlPWhAZUkRjSpVdTrkySqazPorYVTfFe8KZSnRqeomtUa+Lyh9QaiuyB8xGXvdEhb8vy/PahUWgMYLzBXkAGH4XJlbaEMCKI7HsTx7RwNybLdpdAot3uHDQVMH3TeWmDydFwDQNMnh38Q5OT+9pzguOxf9Za7cGBjwRi416n+HF3LfcwSa+AqVn5dB3iWVzGuHkbfAdw5dput8JnV45go0EgV6QgpwSc7zmvnn2nss357nmO+en15QM0ZuEcXOzetmDLkG7WW/uMR7o2rIxLjv2BX9dgCBc5NxBTsyY8JAqK/pelM8FIbsURSgUyajzG3AI=
