language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  sauce_connect: true
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi
env:
  global:
  - secure: y61biuz2CtCvqMzA2e+puwg5CMteSp3AuiGG5LyLwsvIz8JPrK/8XIAQ9RzE/hJb9xYlIlQP22Q8eem+/G1tM2Ma26EgBiJ3kdkILqwR8bMgkNxiR0sAUbDP8sAeES4CefXUVuuJlsI5BWE3zpCilpclJI3zodWjHVGyX13NxndoF/l2aLILc0A/rrAFpCqMw8od/r5LxxMMElU5Es2EMUw5JM+DwmtlN+QOD+V1KRW9SppTB9lpRjsG7IHNF4guOditkKYBJJlu29HQt8x9GsaFIIXj3DLu0mnFzeOVC6f92zqnD57H3Q8iEpbTtnE55dAnlJ9kh0euiFEimWtMHgQVkl+7i9THtk1LQwPoUSo1A1axMDDrH3Mw5lVPFQCmNr+4Jz3XgUxphudhM4q03D8WyIZcdIPggtMfvBTakygF5PeKm28EyxYCh90DbAyLf3hDdT0yRLny8zqbV13lMyAxW1JPLI50EL6h1z9/ZOBXIS2HAuW1OuZd4qlMarQaejBoOISMPrcuuAGVy8nFCb/DbwnGPUnY6t2UtBe1e3zjybM0GfDT01y0Cp1Qbxi11BOIhh5EndOKW4u67PQEiKLu26dMnFQJCc5DRxAP2P18FJaUFvB2p2PjsaLYgjm0/SqdGAdQSSgoPct/OcfYjQjShhNYZuJJ7DNufb9CH4s=
  - secure: eiA1xz8jfQI7G7k6/4plC89zGJDfIJxGkWxcOHaMGA/lnteWyddwU5DUEGyluVg3CTRoRjm7DOWRIF5f1gURUc+4oKfX98n4gfFOOihIOUfhDPoClTtGEy8in2su9BTxrbijqvfUyKq94dR+U7kjvd4/DH17K8Me4pre9wsMyokCh56MBGPPn9xuGEezAESzXsCpK2SzkAMdH7zWHRYv7p5bvX7P1rWVEKL1nM26RW/682LUXbIrsk3AKBuHBAS4EXCS1yicnnrMxa6wrhAmOT85AGjBJwlSfgmLpHPnLgtuts/1xE2HQh7vV/90oGsUn+9qrUemFcvTejKo5Hpb0dNVgqI4wVvzQrUtJYiZ6S6Ae/cxjn7NplBYDuZEHdIgyXznUj8d1v50CQOexKIuPeq2DaOe8a0RjFeDl0WsLfkbIuwNqXoSyLWoCK1XJrePI1q/rIWs5edNLT+0z03l/YwlsTyiqOlmEpdKxT4+JcTy94Pe6lA+adFnZwbgx+4WSJ60/jTjcjIK1V3a65wv9PRW+uFuz3b5le8eE3a097FejifJ0WPNJhvh1OFqLHvcLcbARwJt9VkeXSBeTODEx0N0FwewRNxPT8xpMHTgyF9b601+WqwOvWJXGEyfIwnxjWjhdVdiSbIunv6Jd1OfsuoplHzkXhcP5Eca5CGv0/0=
